### PR TITLE
Fix Website Accessibility issues

### PR DESCRIPTION
**Pull request by purna135**
Fixes https://github.com/pymc-devs/pymcon_2022/issues/166

### CODE REVIEW

**Comment by purna135** [comment]
Hi @OriolAbril. I fixed some of the issues that were reported here: https://wave.webaim.org/report#/https://purna135.github.io/pymcon-test/
There are only a few left, and I need your help to address them.


I'm not sure why it's showing two images in the footer when we only have one.

image
image

**Comment by purna135** [comment]
Also, kindly help me in improving the link descriptions.

**Comment by OriolAbril** [comment]
Thanks, it looks great. In the preview you shared I see 3 issues: 1 contrast error and 2 alerts.

The contrast error is in the register now/submit a proposal button. There, the background color is `#23929E` and the text color is white which is too little contrast. The section "join the discourse" has a similar background color, but it is `#1D7996` there which has more contrast. I don't know which of the two colors is the one in the pymcon color palette, but we should probably use that one and then black for text (that changes to white on hover) if 23 or keep the always white text if 1D... color.

The first alrert is the justified text in the "our goals" section. We can change this to left aligned to fix it.

The 2nd alert is the same alt text for two "close" images. I understand it means the navbar and footer images as they are the same image and both have the same alt text. I actually hadn't realized until now that the logo in the footer was a link. I think here we can make the logo at the footer a decorative image (with "" as alt text and no link). The navbar is always visible, so people can always go to the homepage clicking on the nabvar logo. And if we really want a 2nd back to homepage link we can add 1 more element to permalinks section in footer.

I think the alt text suggestions are fine, if needed we can continue to improve on them in future PRs.

**Comment by purna135** [comment]
Thank you @OriolAbril 
I fixed the Contrast Errors and Alerts, please have a look on review here, https://wave.webaim.org/report#/https://purna135.github.io/pymcon-test/

**Review by OriolAbril — APPROVED** [review]
Thanks!

**Pull request merged**
