### PR TITLE
Add Todd's event Discourse link

### PR DESCRIPTION
**Pull request by purna135**

### CODE REVIEW

**Comment by reshamas** [comment]
@purna135 
Trying to understand what the purpose of the zip file is?
Do people have to download the zip file, unzip it and then watch the recording?
Would it be easier to upload the video to PyMC?

This is linked on the Discourse post:
https://discourse.pymc.io/t/pymcon-web-series-06-protecting-voting-rights-with-pymc-may-24-2023-todd-hendricks/12131

Screen Shot 2023-05-15 at 3 34 51 PM

**Comment by purna135** [comment]
I think we can temporarily remove this link and incorporate it later, subsequent to editing and uploading the video to YouTube.

**Comment by purna135** [comment]
Hi @canyon289,

Taking into account Reshamas's feedback, I have removed the link and temporarily replaced it with a placeholder stating "coming soon." Considering my current limitations with a slow network, I kindly request your assistance in uploading the video to YouTube sometime in this week, then I will add the video link to discourse post.

Thank you

**Comment by canyon289** [comment]
definitely I'll upload it. thanks for the heads up

**Comment by canyon289** [comment]
Done! https://youtu.be/dbkgpePWePg

**Pull request merged**
