### PR TITLE
Add Sponsors Page

### PR DESCRIPTION
**Pull request by purna135**
Fixes #51 

Preview can be found [here](https://purna135.github.io/pymcon-test/sponsors/)

### CODE REVIEW

**Comment by purna135** [comment]
Hi @reshamas. @OriolAbril, Please have a look at the [preview](https://purna135.github.io/pymcon-test/sponsors/), and I will be waiting for your suggestions on how to improve it.

**Comment by reshamas** [comment]
@purna135 
Copying my comments from here:  https://github.com/pymc-devs/pymcon_web_series_website/issues/36#issuecomment-1336526389

~~a) For "(Contact us for custom sponsorships)", can you link directly to the "Contact" page?~~
~~b) Where are the form messages going, which email address? Is someone monitoring that now? I sent in a couple of test messages.~~
c) At the bottom, can we add in the "PyMCon 2020 Sponsors" and their logos in?
d) Where it currently says "PyMCon 2020 Sponsors" at the top can we update it to "PyMCon 2023 Sponsors" and add a blank logo in that says "Sponsor PyMCon" and link that to the "Contact" page?
~~e) email address here is: [pymconference@gmail.com](mailto:pymconference@gmail.com), but it should be [pymcon@pymc-devs.org](mailto:pymcon@pymc-devs.org)~~


References #36

**Comment by reshamas** [comment]
@purna135 I see you uploaded the logos from 2020 in this PR, but I don't see them in the preview.

**Comment by reshamas** [comment]
@purna135 OK, I think this looks GOOD! Thanks!!

**Pull request merged**
