### PR TITLE
Add link straight to an event in the events page

### LINKED ISSUE #118: Is there a way to link straight to an event in the events page?
Is there a way for each card in the events page itself to get a url say if I want to link directly to Todds event?

https://pymcon.com/events/
image

Here's an example from Discourse where I can link straight to Christian's post.
https://discourse.pymc.io/t/nonetype-error-on-custom-distribution/12176/2

### PR DESCRIPTION
**Pull request by purna135**
Fixes #118 
Each event now has a unique ID and a button that allows you to copy the link to that specific event.

### CODE REVIEW

**Comment by canyon289** [comment]
I think its better to leave the button not disabled in case someone wants to copy again, the check mark looks great. Having the link is quite nice!

**Comment by purna135** [comment]
> I think its better to leave the button not disabled in case someone wants to copy again

done

We can keep two types of links:

1. pycom.com/event/#eventNumber (e.g., pycom.com/event/# 8)
2. pycom.com/event/#eventTitle (e.g., pycom.com/event/#automatic-probability-with-pymc)

Which of these options do you prefer?

**Comment by canyon289** [comment]
Hey sorry I missed this,
Title is better,

**Comment by purna135** [comment]
> Title is better,

done ✅, please have a look

**Pull request merged**
