### PR TITLE
enable sponsors page

### PR DESCRIPTION
**Pull request by reshamas**

### CODE REVIEW

**Comment by reshamas** [comment]
@purna135 @canyon289 
I thought I would see a preview link, but don't see it ?

**Comment by canyon289** [comment]
not sure, I think @mjhajharia had setup the netlify preview though vaguely remember it being disabled

**Comment by OriolAbril** [comment]
I think #36 now superseedes this PR even if it's an issue instead of a PR, but mostly wanted to get the two linked together

**Comment by mjhajharia** [comment]
> 

I did, it was on the previous repository. the previews happened through netlify, netlify does not have access to this repository, i tried reconfiguring it today i think one of the admins should have gotten a request for netlify's access to this repository. i'll check again later today

**Pull request closed without merging**
