### PR TITLE
Add links to videos for events past

### PR DESCRIPTION
**Pull request by reshamas**

### CODE REVIEW

**Comment by cluhmann** [comment]
This is great.  Two things. First, I think the text "Discourse Post" is going to be confusing because many people don't know what "Discourse" (the platform) is.  Maybe something like "Details" instead?  Second, the links are a bit squished together on browser, so that it doesn't look like 3 separate "buttons".  Is there any way to get some horizontal separation between them?

image

**Comment by canyon289** [comment]
Echoing what Christian said

**Comment by reshamas** [comment]
>First, I think the text "Discourse Post" is going to be confusing because many people don't know what "Discourse" (the platform) is. Maybe something like "Details" instead? 

Previously it was "Learn more".  I am not sure it is an issue if people have not heard of Discourse. As a user, if I hadn't heard of Discourse, I would click on the link anyway to see where it led me.

>Second, the links are a bit squished together on browser, so that it doesn't look like 3 separate "buttons". Is there any way to get some horizontal separation between them?

I agree the buttons need a bit of spacing. I did try a few things but couldn't figure it out. I don't have the experience to add a space. I would probably accept as is and open an issue for style preference.

**Review by cluhmann — APPROVED** [review]
I think we can merge this. I will open an issue about the button squishing.

**Pull request merged**
